### PR TITLE
Explorer GUI

### LINKED ISSUE #13: Add a map "explorer" GUI
Basically a double chest-like UI that would list all the maps the user has.
Taking a map from it would actually give the user a copy of this map, as if requested using /maptool get.
Right-clicking a poster map would open another GUI that lists all the map parts of the poster, arranged like they would be in the world (i.e. using their rows and columns, if this data is available).
Putting a map in the inventory would remove (or refund) it, but putting any other item would simply cancel the event.

If the amount of maps is too large for the GUI to show, scrollbar-like arrows will appear on the sides of the GUI (vertical only for the global map GUI, both if necessary for the poster map GUI) : 

````
OOOOOOOO^
OOOOOOOO
OOOOOOOO
OOOOOOOO
OOOOOOOOv
<       >

(O = inventory slot)
````

Arrow hover-text would show the total amount of pages as well (example : "Go to page 2 of 9").

### PR DESCRIPTION
**Pull request by AmauryCarrade**
This PR is intended to close #13, by:

 - [x] adding an “explorer” per-category & paginated GUI;
 - [x] allowing the user to get a map by clicking on it on the GUI;
 - [x] allowing him to remove a map or a poster from his inventory by putting it on the GUI (removes all the maps from the poster, if it's a poster);
 - [x] allowing him to preview the posters in the GUI;
 - [x] allowing him to get only one map of a poster by clicking on it on this preview screen;
 - [x] allowing him to remove a map or a poster directly from the GUI, on this preview screen;
 - [x] allowing him to rename a map (opinion? best method to do that?);
 - [x] allowing him to see his stats on the main GUI (currently category selector): maps created, limit, percentage used (opinion?).

This is obviously an early PR—don't merge now.

### CODE REVIEW

**Comment by AmauryCarrade** [comment]
Can we update the dependency to Bukkit 1.8.3+?
To be able to use the [`ItemMeta.addItemFlags(ItemFlag ...)`](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/meta/ItemMeta.html#addItemFlags(org.bukkit.inventory.ItemFlag...)) method.

**Comment by AmauryCarrade** [comment]
Nevermind—reflection ftw.

**Comment by AmauryCarrade** [comment]
I want to add a `@GUIAction` annotation to the new GUI API—this for two reasons.

1. To enhance the code's readability.
2. To be able to say to my IDE (IntelliJ): « these methods ARE used ».
    Unused methods warning of IntelliJ

This annotation would not be kept at runtime, because there's no runtime usage.  
Something just like the `@Override` annotation, in fact.

@prokopyl Your opinion?

**Comment by prokopyl** [comment]
I don't like the idea of adding annotations that have no value. 
That would mean that the developer can easily see action methods in his code through a specific annotation, but the API behind it can't ? That just seems silly to me.

It would be better to add a GuiAction annotation, and rely exclusively on it to fetch the event handlers. This way the annotation isn't just decorative, and it allows to bind action to public methods (like the pagination methods in ExplorerGui).

On a side note, you are creating all of your items manually, why ? The GuiUtils.makeItem() methods are here for this exact purpose.

**Comment by AmauryCarrade** [comment]
> On a side note, you are creating all of your items manually, why ? The GuiUtils.makeItem() methods are here for this exact purpose.

Some because the tooltips are constructed; some others because of a copy/paste from the old GUIs. But I'll use these methods when possible.

> I don't like the idea of adding annotations that have no value.
That would mean that the developer can easily see action methods in his code through a specific annotation, but the API behind it can't ? That just seems silly to me.

> It would be better to add a GuiAction annotation, and rely exclusively on it to fetch the event handlers. This way the annotation isn't just decorative, and it allows to bind action to public methods (like the pagination methods in ExplorerGui).

I like this idea, I'll see what's the best method to implement this—except if you want to do so.
This said, I don't think source-code-only annotations are useless, but well, it's just another opinion.

**Comment by prokopyl** [comment]
> Some because the tooltips are constructed.

I suppose that by "constructed" you mean they are generated during runtime (like "Page x / n") ?
If so, what prevents you to use the GuiUtils methods in that case ?
(Although I agree the ability to use formatted strings could be useful).

> I like this idea, I'll see what's the best method to implement this—except if you want to do so.

I think i'll do it, I have some spare time today, plus I already have some ideas in mind.

> This said, I don't think source-code-only annotations are useless, but well, it's just another opinion.

I didn't say they were completely useless. But to me they are adding an extra notion to the code (or even the language, in the case of `@Override`), for something that should be in the integrated documentation, as its only use is readablility.
 It's confusing for new programmers (you have to add something that does nothing), and just annoying for the experienced ones (for the same reason, although most IDEs can do it for you).
But like you said, opinions ... :-)

**Comment by prokopyl** [comment]
Also, in a recent commit you allowed callbacks to access the `InventoryClickEvent`, but you didn't use it anywhere. Why did you need that for ?

**Comment by AmauryCarrade** [comment]
> I suppose that by "constructed" you mean they are generated during runtime (like "Page x / n") ?
If so, what prevents you to use the GuiUtils methods in that case ?
(Although I agree the ability to use formatted strings could be useful).

I also mean “conditionally constructed tooltips”—such items cannot be created using the `GuiUtils` methods, except with intermediate variables or ternary statement... But I think these codes are not very readable.

Examples of such items are the statistic book and the maps items in the main list.

   


> I think i'll do it, I have some spare time today, plus I already have some ideas in mind.

OK, I'll not get into that.
   

> I didn't say they were completely useless. But to me they are adding an extra notion to the code (or even the language, in the case of `@Override`), for something that should be in the integrated documentation, as its only use is readablility.
It's confusing for new programmers (you have to add something that does nothing), and just annoying for the experienced ones (for the same reason, although most IDEs can do it for you).

I don't think an extra line is *annoying*, and it increase readability. This said you're right on some points—except the one about `@Override`, because this annotation is also used by the compiler to produce an error if misplaced, so it's not **only** here for readability. But that's not the point of this discussion.
   

> Also, in a recent commit you allowed callbacks to access the `InventoryClickEvent`, but you didn't use it anywhere. Why did you need that for ?

I'm using—or will use—this GUI utility in other projects, and want to add the possibility. I initially added this to the `unknown_action` method, and I added the argument to other callback methods, for coherence reasons and because who know what we'll need to do in this methods.
Feel free to remove them if you don't like them, but they are there (tl;dr) “just in case” and because I needed them in the `unknown_action` method in another project.

By the way, the main use I see is the access to the `event.isRightClick()` method (this is why I needed them).

**Comment by prokopyl** [comment]
Well, I ended up doing much more than just the annotations, mainly to fix various bugs that were recently introduced.
I am a bit too lazy to make a full review here, come on Skype if you want to discuss some points. :-)

**Comment by prokopyl** [comment]
Everything  in the to-do list has been implemented using zLib components, and I see no bugs remaining, so I think it is time to merge this.

**Comment by AmauryCarrade** [comment]
o/

**Pull request merged**
