### PR TITLE
Fix saving images

### PR DESCRIPTION
**Pull request by GriffinCodes**
Undo comments from https://github.com/zDevelopers/ImageOnMap/commit/3753a03ef33d5100ed4192abf3682db0d64b1d0b (Presumably made for testing?)

Admin made 58 images before realizing :upside_down_face:

### CODE REVIEW

**Comment by Vlammar** [comment]
Was trying to fix this https://github.com/zDevelopers/ImageOnMap/issues/104 . In the end there is still a memory leak (I've added more flush and removed gc.dispose() that was useless)

**Comment by GriffinCodes** [comment]
I think the main branch should remain functional until the issue can be resolved. Images appear to work and save correctly until the server is restarted, and it caused my admin a pretty big headache.

**Comment by AmauryCarrade** [comment]
Yeah we could use better branches and PRs, I agree and @Vlammar we should talk about that.

This being said, please remember that there is _no guarantee_ on untagged commits! The main branch is not called `indev` for no reason :) .

**Comment by Vlammar** [comment]
@AmauryCarrade do we merge? This commit https://github.com/zDevelopers/ImageOnMap/commit/219869c82b50b7d5ab5acfebc7fb4fb614141ae5  (it's on my dithering branch) do the same thing but resolve some issues with useless flushs and forgotten one

**Comment by AmauryCarrade** [comment]
Let's do that. This was also cherry-picked into our `dithering` branch. Thanks!

**Pull request merged**
