### PR TITLE
Update-bump to 1.13

### PR DESCRIPTION
**Pull request by Xernium**
Not much to say here;
Known gotcha: /maptool list crashes the player @AmauryCarrade any idea? :D

### CODE REVIEW

**Comment by AmauryCarrade** [comment]
Hi, and thanks a lot for your work!

ImageOnMap depends on zLib, which is not yet updated for 1.13.2. That may be the problem. What is the bug exactly? An exception, an error message, something? Actually, I'm quite surprised it runs correctly on the old zLib version, including GUIs and all, seeing all the reflexion and breaking changes involved in 1.13.

Also, did you tested your update on older data too, to ensure upgrade is possible without any problem?

I will review the code soon. Thanks again :)

**Comment by Xernium** [comment]
@AmauryCarrade Tested on older- no I don't have a setup for that.

**Comment by Xernium** [comment]
`[22:58:43 WARN]: [ImageOnMap] NMS Exception while parsing ItemStack to JSON String
fr.moribus.imageonmap.tools.reflection.NMSException: Unable to retrieve Minecraft ID for an ItemStack
	at fr.moribus.imageonmap.tools.items.ItemUtils.getMinecraftId(ItemUtils.java:504) ~[?:?]
	at fr.moribus.imageonmap.components.rawtext.RawText.toJSONString(RawText.java:217) ~[?:?]
	at fr.moribus.imageonmap.components.rawtext.RawTextPart.hover(RawTextPart.java:349) ~[?:?]
	at fr.moribus.imageonmap.commands.maptool.ListCommand.addMap(ListCommand.java:92) ~[?:?]
	at fr.moribus.imageonmap.commands.maptool.ListCommand.run(ListCommand.java:67) ~[?:?]
	at fr.moribus.imageonmap.components.commands.Command.execute(Command.java:167) ~[?:?]
	at fr.moribus.imageonmap.components.commands.CommandGroup.executeMatchingCommand(CommandGroup.java:171) ~[?:?]
	at fr.moribus.imageonmap.components.commands.CommandGroup.executeMatchingCommand(CommandGroup.java:163) ~[?:?]
	at fr.moribus.imageonmap.components.commands.CommandGroup.onCommand(CommandGroup.java:189) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-cpsh.jar:git-Spigot-3cb9dcb-0f708cb]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-cpsh.jar:git-Spigot-3cb9dcb-0f708cb]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-cpsh.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[spigot-cpsh.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-cpsh.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-cpsh.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-cpsh.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-cpsh.jar:git-Spigot-3cb9dcb-0f708cb]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-cpsh.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-cpsh.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-cpsh.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-cpsh.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-cpsh.jar:git-Spigot-3cb9dcb-0f708cb]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchFieldException: REGISTRY
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_191]
	at fr.moribus.imageonmap.tools.reflection.Reflection.getField(Reflection.java:168) ~[?:?]
	at fr.moribus.imageonmap.tools.reflection.Reflection.getFieldValue(Reflection.java:132) ~[?:?]
	at fr.moribus.imageonmap.tools.items.ItemUtils.getMinecraftId(ItemUtils.java:496) ~[?:?]
	... 24 more`

**Comment by Xernium** [comment]
is when you do /maptool list

**Comment by Xernium** [comment]
working on it
also I replaced ItemStackCreator or whatever it was so I could work it on 1.13
Also we should aim for a rewrite and completely use MapView instead of ID's

**Comment by Xernium** [comment]
Edit @AmauryCarrade This error is caused by `rawText.hover(ItemStack<>)` Commenting it out would fix it but I think you should rather update the zLib :D

**Comment by Xernium** [comment]
Bildschirmfoto 2019-03-09 um 23 06 01

**Comment by Xernium** [comment]
Edit 2: forgot to put `Commands.registerShortcut("maptool", ExploreCommand.class, "maps");` back in the Plugin-Main

**Comment by Xernium** [comment]
Edit 3: Forgot to change the POM.xml

**Comment by Xernium** [comment]
Had time yet? Sorry to bug you

**Comment by Xernium** [comment]
- [x] Conversion works, nothing there needs changing    
- [ ] zLib needs updating to 1.13
also @AmauryCarrade It'd be great if you didn't use your own registered enchantments as they tend to cause crashes on the Players (try to put something with a registered enchantment in an anvil and you'll see what I mean quickly)

**Comment by Xernium** [comment]
@PurpleStormCloud Are you free for the rebase of zLib?

**Comment by PurpleStormCloud** [comment]
No. I ain't doing that. :') I got enough stuff on my plate

**Comment by Giuseppington** [comment]
Know it's discontinued but it cant hurt,

Don't know if this helps, but single maps work if you delete them before placing them. 

Did the following:

1.) /tomap <url>

2.) Drop map

3.) /maptools explore

4.) delete the map.

Is there a way to disable maps being saved after creation? Even though the UI becomes pointless it makes the core purpose of the plugin functional.

**Comment by Movion** [comment]
Aaaand.. there goes my hope for a 1.13 version ...

**Comment by Xernium** [comment]
@Movion It’s not done entirely. I am making a maintainable replacement for this plugin. Stay tuned.

**Pull request closed without merging**
