### PR TITLE
Add save-full-image and limit-size-x and limit-size-y

### PR DESCRIPTION
**Pull request by kirbykirby56**
Now you can save the full image! Also, limit size x / y implemented.

### CODE REVIEW

**Comment by jewome62** [comment]
This is an implementation for #34 
I need that's for install on my server.
Do you intend to treat these PR ?

**Comment by AmauryCarrade** [comment]
I'll try to test and merge it soon (as soon as I have 1.15 support, or maybe you don't need that?)

**Comment by jewome62** [comment]
@AmauryCarrade Oh I'm blocked to 1.13 with calamitous support from FAWE in the following versions :sweat_smile:

**Comment by Vlammar** [comment]
We were planning to do something close, we tought that it will be easyier to limit the number of map used for render (unlimited for op).

**Comment by jewome62** [comment]
OK, I can't wait to test this

**Comment by jewome62** [comment]
Any news ? @Vlammar

**Comment by Vlammar** [comment]
Hey sorry I am a bit overcrowded right now, I have reviewed your pull request.

**Pull request merged**
